cache:
  directories:
    - $HOME/.cache/rebar3
    - $TRAVIS_BUILD_DIR/_build
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 19.0
  - 18.3
  - 17.5
script: "./bin/rebar3 eunit"
sudo: false
